### ISSUE TITLE
Proposal to not use unicode_literals

### ISSUE THREAD

**Issue by mitsuhiko** [PythonCharmers/python-future#22]
I want to propose not using unicode_literals for this undertaking.  Only a very low number of people are using Python 3.2 or older and being explicit about unicode strings makes Python code less error prone.

Accidentally upgrading docstrings and other things to unicode has very bad consequences which can go unnoticed for a really long time.  I have seen people putting unicode strings into WSGI dictionaries, breaking pydoc because of unicode docstrings, Django breaking filesystem access due to accidentally using unicode paths etc.

I like the idea of python future a ton, and just started looking into it, but I am really not a fan of the idea of proposing people to use unicode literals.

**Comment by spookylukey** [comment]
A very late reply to this issue, from someone surprised by the advice that click was giving me:

Armin mentions some examples of problems caused by `unicode_literals` in Django. If you check more carefully, [ticket 2167](https://code.djangoproject.com/ticket/21627), [ticket 21358](https://code.djangoproject.com/ticket/21358) and [ticket 21627](https://code.djangoproject.com/ticket/21627) are actually counter examples (the fixes involved adding `unicode_literals`) and [ticket 20809](https://code.djangoproject.com/ticket/20809) was marked as not-a-bug - the behaviour introduced by `unicode_literals` was welcome.

My own experience is that `unicode_literals` was the only way to fix a continual source of unicode errors in Python 2 code bases with large number of strings that were intended to be unicode, but people just kept forgetting to add the `u` prefix.
