### ISSUE TITLE
Running test.py when importing moves

### ISSUE THREAD

**Issue by drecker** [PythonCharmers/python-future#497]
When running the code:
```
from future import moves
```
(or importing anything within `moves` module)

It actually runs the `test.py` file in **current working directory**.

Python: 3.6.8
future: 0.17.1

Detailed how-to reproduce:
```
user:~$ cd /tmp/

user:/tmp$ virtualenv -p python3 crash_test
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/crash_test/bin/python3
Also creating executable in /tmp/crash_test/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

user:/tmp$ source crash_test/bin/activate

(crash_test) user:/tmp$ pip install future
Collecting future
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Building wheels for collected packages: future
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.17.1-cp36-none-any.whl size=488730 sha256=9b66f34610c5236d9dbd29832590042bb8814462c3b8c3fc2e684d4b353ccc8f
  Stored in directory: /home/user/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built future
Installing collected packages: future
Successfully installed future-0.17.1

(crash_test) user:/tmp$ echo "raise RuntimeError('Running test.py')" > test.py

(crash_test) user:/tmp$ echo "from future import moves" > crash.py

(crash_test) user:/tmp$ python crash.py 
Traceback (most recent call last):
  File "crash.py", line 1, in <module>
    from future.moves.urllib.parse import urlparse
  File "/tmp/crash_test/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/tmp/crash_test/lib/python3.6/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/tmp/crash_test/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/tmp/test.py", line 1, in <module>
    raise RuntimeError('Running test.py')
RuntimeError: Running test.py
```

**Comment by QuLogic** [comment]
`test` is the name of a [standard library package](https://docs.python.org/3/library/test.html). You should not name your file `test.py`.

**Comment by drecker** [comment]
I agree it is not-the-best name at least, but it is not forbidden and should not cause buggy behavior.

That being said, I think this crash is quite unfortunate. How I came across this: I was debugging my code and wrote short (about 5 line of code) script causing crash within my code, as this was just testing script with life-span of couple of minutes, I just named it a `test.py` (no where in my code i `import test`). It took me a while to understand that the package installed via pip actually runs the local file. I imagine that this is not so unlikely scenario.

**Comment by drecker** [comment]
PS: That is for my justification to file it as a bug, as for the severity (and when/if it is worth fixing) -- it is, of course, up to the dev(s)

**Comment by jmadler** [comment]
I hear you -- this seems like a painful developer experience.  

I can imagine sitting down to prototype some feature in a randomly named file in my home directory and not even knowing I had a 'test.py' in that directory.  The errors that result could be very subtle if I have a local fork of test, for example, with some local patches.

The only way I can think of to address this in future is to manipulate sys.path at that point in the code depending on the entrypoint's filename, or to throw a warning of some kind.  Modifying the behavior would make the library less predictable and potentially introduce bugs if others' codebase includes this usage pattern intentionally.  A warning would be noisy for those users, but helpful for users like yourself.

Since this footgun could appear in any library (though so far I can't find any other instances of it), I think it might make sense to have this discussion with the Python development team.  It may be appropriate to address at the interpreter level.

FWIW this problem doesn't appear in other languages -- Perl for example, by convention, uses different case structure for entrypoints and libraries.  It also doesn't really have a standard library.  Thus the same importing path logic can be applied without this problem appearing.

**Comment by ankostis** [comment]
Dupe of #268.
